apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-backend-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-backend-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-frontend-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-frontend-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-database-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: architecture-study-database-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: github-actions
